import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { accounts, errorText } from "../api/accountsClient";
import type { Dashboard, Watchlist } from "../api/types";
import { AppShell, DateTime, ErrorPanel, Loading, Money } from "../components/ui";

export function DashboardPage() { const [data, setData] = useState<Dashboard>(); const [error, setError] = useState(""); const load = () => accounts.dashboard().then(setData).catch(e => setError(errorText(e))); useEffect(() => { void load(); }, []); return <AppShell>{!data && !error ? <Loading /> : <><div className="page-head"><div><h1>Paper-trading dashboard</h1><p className="muted">One configured Alpaca account powers this installation.</p></div><button onClick={() => accounts.reconcile().then(setData).catch(e => setError(errorText(e)))}>Reconcile now</button></div>{error && <ErrorPanel message={error} />}{data && <><section className="grid"><Metric label="Cash" value={<Money value={data.account?.cash} />} /><Metric label="Equity" value={<Money value={data.account?.equity} />} /><Metric label="Portfolio value" value={<Money value={data.account?.portfolioValue} />} /></section><p className="muted">Data: {data.freshness} · last synchronized <DateTime value={data.asOf} /></p><section className="panel"><h2>Positions</h2><table className="data-table"><thead><tr><th>Symbol</th><th>Quantity</th><th>Market value</th></tr></thead><tbody>{data.positions.map(position => <tr key={position.symbol}><td>{position.symbol}</td><td>{position.quantity}</td><td><Money value={position.marketValue} /></td></tr>)}</tbody></table></section></>}</>}</AppShell>; }
function Metric({ label, value }: { label: string; value: React.ReactNode }) { return <section className="panel metric"><label>{label}</label><strong>{value}</strong></section>; }
export function WatchlistsPage() { const [items, setItems] = useState<Watchlist[]>([]); const [name, setName] = useState(""); const [symbols, setSymbols] = useState(""); const [error, setError] = useState(""); const load = () => accounts.watchlists().then(setItems).catch(e => setError(errorText(e))); useEffect(() => { void load(); }, []); const create = async () => { try { const result: any = await accounts.createWatchlist(name, symbols.split(",").map(x => x.trim()).filter(Boolean)); window.location.assign(`/watchlists/${result.watchlist.watchlistId}`); } catch (e) { setError(errorText(e)); } }; return <AppShell><h1>Watchlists</h1>{error && <ErrorPanel message={error} />}<section className="panel form"><label>Name<input value={name} onChange={e => setName(e.target.value)} /></label><label>Symbols (comma-separated)<input value={symbols} onChange={e => setSymbols(e.target.value)} /></label><button onClick={create}>Create watchlist</button></section><section className="panel"><ul>{items.map(item => <li key={item.watchlist.watchlistId}><Link to={`/watchlists/${item.watchlist.watchlistId}`}>{item.watchlist.name}</Link> ({item.entries.length} symbols)</li>)}</ul></section></AppShell>; }
export function WatchlistDetailPage() { const { watchlistId = "" } = useParams(); const nav = useNavigate(); const [data, setData] = useState<Watchlist>(); const [ticker, setTicker] = useState(""); const [error, setError] = useState(""); const load = () => accounts.watchlist(watchlistId).then(setData).catch(e => setError(errorText(e))); useEffect(() => { void load(); }, [watchlistId]); if (!data) return <AppShell>{error ? <ErrorPanel message={error} /> : <Loading />}</AppShell>; return <AppShell><h1>{data.watchlist.name}</h1><div className="actions"><input placeholder="AAPL" value={ticker} onChange={e => setTicker(e.target.value)} /><button onClick={() => accounts.addTicker(watchlistId, ticker).then(load).catch(e => setError(errorText(e)))}>Add symbol</button><button className="danger" onClick={() => accounts.deleteWatchlist(watchlistId).then(() => nav("/watchlists")).catch(e => setError(errorText(e)))}>Delete</button></div>{error && <ErrorPanel message={error} />}<ul>{data.entries.map(entry => <li key={entry.ticker}>{entry.ticker} · {entry.active ? "active" : "inactive"} <button onClick={() => accounts.toggleTicker(watchlistId, entry.ticker, !entry.active).then(load)}>Toggle</button><button onClick={() => accounts.removeTicker(watchlistId, entry.ticker).then(load)}>Remove</button></li>)}</ul></AppShell>; }
export function NotFoundPage() { return <AppShell><h1>Page not found</h1><Link to="/dashboard">Return to dashboard</Link></AppShell>; }
